"""initial_schema

Revision ID: 2caa6c789422
Revises: 
Create Date: 2026-06-04 15:26:35.154934+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2caa6c789422'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('orientation', 'memory_recall', 'long_term_memory', 'emotional_wellbeing', name='question_category'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('elderly', 'caregiver', 'healthcare', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('caregiver_patient_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregiver_pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_user_id')
    )
    op.create_table('checkin_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status'), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processing_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_sessions_patient_user_id'), 'checkin_sessions', ['patient_user_id'], unique=False)
    op.create_table('guidance_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='guidance_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('session_context_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_messages_caregiver_user_id'), 'guidance_messages', ['caregiver_user_id'], unique=False)
    op.create_table('healthcare_patient_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcw_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hcw_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('baseline_established', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('checkin_count', sa.Integer(), nullable=True),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_patient_user_id'), 'reports', ['patient_user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_patient_user_id'), 'alerts', ['patient_user_id'], unique=False)
    op.create_table('care_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('cognitive', 'social', 'medical', 'routine', 'wellbeing', name='recommendation_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_recommendations_patient_user_id'), 'care_recommendations', ['patient_user_id'], unique=False)
    op.create_table('checkin_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('recording_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_delay_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['checkin_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facial_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('video_duration_seconds', sa.Float(), nullable=True),
    sa.Column('face_detected', sa.Boolean(), nullable=True),
    sa.Column('face_detection_confidence', sa.Float(), nullable=True),
    sa.Column('avg_response_delay_seconds', sa.Float(), nullable=True),
    sa.Column('facial_risk_score', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('raw_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('language_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('orientation_score', sa.Float(), nullable=True),
    sa.Column('memory_recall_score', sa.Float(), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_score', sa.Float(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=50), nullable=True),
    sa.Column('language_risk_score', sa.Float(), nullable=True),
    sa.Column('raw_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('voice_component', sa.Float(), nullable=True),
    sa.Column('language_component', sa.Float(), nullable=True),
    sa.Column('facial_component', sa.Float(), nullable=True),
    sa.Column('memory_component', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('main_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_risk_scores_patient_user_id'), 'risk_scores', ['patient_user_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('voice_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('speech_rate_wpm', sa.Float(), nullable=True),
    sa.Column('hesitation_count', sa.Integer(), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('avg_pause_duration', sa.Float(), nullable=True),
    sa.Column('voice_risk_score', sa.Float(), nullable=True),
    sa.Column('raw_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('file_type', sa.Enum('audio', 'video', 'combined', name='media_file_type'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['checkin_answers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_files')
    op.drop_table('voice_analysis_results')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_risk_scores_patient_user_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('language_analysis_results')
    op.drop_table('facial_analysis_results')
    op.drop_table('checkin_answers')
    op.drop_index(op.f('ix_care_recommendations_patient_user_id'), table_name='care_recommendations')
    op.drop_table('care_recommendations')
    op.drop_index(op.f('ix_alerts_patient_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_reports_patient_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('patients')
    op.drop_table('healthcare_patient_links')
    op.drop_index(op.f('ix_guidance_messages_caregiver_user_id'), table_name='guidance_messages')
    op.drop_table('guidance_messages')
    op.drop_index(op.f('ix_checkin_sessions_patient_user_id'), table_name='checkin_sessions')
    op.drop_table('checkin_sessions')
    op.drop_table('caregiver_pins')
    op.drop_table('caregiver_patient_links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('checkin_questions')
    # ### end Alembic commands ###
